services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: glop
      POSTGRES_PASSWORD: glop
      POSTGRES_DB: glop
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
